class ApplicationController < ActionController::Base
  #skip the csrf token generated by the rails system since we are going to request from an external front end app
  skip_before_action :verify_authenticity_token
end
